# Generated by Django 3.1.4 on 2020-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_firstname', models.CharField(max_length=50)),
                ('teacher_lastname', models.CharField(max_length=50)),
                ('teacher_email', models.EmailField(max_length=50)),
                ('teacher_address', models.CharField(max_length=200)),
                ('teacher_number', models.IntegerField(max_length=10)),
                ('when_created', models.DateField()),
                ('creator_teacher', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'studentDetails',
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('adminId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('admin_firstname', models.CharField(max_length=50)),
                ('admin_lastname', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=50)),
                ('admin_address', models.CharField(max_length=200)),
                ('admin_phone', models.IntegerField(max_length=10)),
                ('when_created', models.DateField()),
            ],
            options={
                'db_table': 'adminDetails',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('teacher_firstname', models.CharField(max_length=50)),
                ('teacher_lastname', models.CharField(max_length=50)),
                ('teacher_email', models.EmailField(max_length=50)),
                ('teacher_address', models.CharField(max_length=200)),
                ('teacher_phone', models.IntegerField(max_length=10)),
                ('when_created', models.DateField()),
                ('creator_admin', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teacherDetails',
            },
        ),
    ]
