# Generated by Django 3.1.4 on 2020-12-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='admin_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_phone',
            field=models.IntegerField(),
        ),
    ]
