# Generated by Django 3.1.4 on 2020-12-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20201211_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher_address',
            new_name='student_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher_lastname',
            new_name='student_lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher_number',
            new_name='student_phone',
        ),
    ]
