# Generated by Django 3.1.4 on 2020-12-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20201211_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='admin_phone',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_phone',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
