# Generated by Django 3.1.4 on 2020-12-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20201211_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='admin_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_phone',
            field=models.BigIntegerField(),
        ),
    ]
