# Generated by Django 3.1.4 on 2020-12-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20201211_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='creator_teacher',
            new_name='creator_teacherId',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='creator_admin',
            new_name='creator_adminId',
        ),
    ]
