# Generated by Django 3.1.4 on 2020-12-12 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20201212_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='when_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='when_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='when_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
