# Generated by Django 3.1.4 on 2021-04-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20210407_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='superadmin',
            old_name='adminId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacherId',
            new_name='id',
        ),
    ]
