# Generated by Django 3.1.4 on 2021-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20210407_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentPass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='superadmin',
            old_name='adminPass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacherPass',
            new_name='password',
        ),
    ]
